<a href="https://colab.research.google.com/github/AmarnadhReddy055/Multi-Model-Hate-Speech-Detection-In-Memes/blob/main/ImageUniModels.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import ast

In [2]:
train_image=pd.read_csv('/content/drive/MyDrive/train_image.csv')

In [3]:
dev_image=pd.read_csv('/content/drive/MyDrive/cross_validation_image.csv')

In [4]:
train_image.dropna(inplace=True)

In [5]:
train_image.reset_index(inplace=True)

In [6]:
train_image.head()

index    id        img  label  \
0      0  1235  01235.png      1   
1      1  1236  01236.png      0   
2      2  1243  01243.png      0   
3      3  1245  01245.png      1   
4      4  1247  01247.png      1   

                                                text  \
0  when you're feeling horny asf but your habibi ...   
1                   meanwhile at the isis strip club   
2  when your human says "who' s a good girl?" and...   
3  and that was the last nativity play my son was...   
4      you can't be racist if there is no other race   

                                            features  
0  [0.71356636, 0.4687377, 0.7601375, 0.47391602,...  
1  [0.7574666, 0.49860162, 0.8951834, 0.45049658,...  
2  [0.8522473, 0.49101305, 0.8114812, 0.43492022,...  
3  [0.81344944, 0.42663395, 0.7078128, 0.45056176...  
4  [0.75893325, 0.44350454, 0.7556687, 0.39917853...

In [7]:
dev_image.head()

id        img  label                                               text  \
0  1268  01268.png      0  father and daughter bonding time is the best l...   
1  1456  01456.png      1            they see them rollin..... they hating..   
2  1726  01726.png      1        a real man loads the dishwasher every night   
3  1742  01742.png      0  in just one hour from now i'll only have 4 hou...   
4  1765  01765.png      1  after a girl dies, what organ in her body stay...   

                                        cleaned_text  \
0  father daughter bonding time best like share a...   
1                                  see rollin hating   
2               real man load dishwasher every night   
3              one hour ill hour left work mere hour   
4                  girl dy organ body stay warm dick   

                                            features  
0  [0.8011039, 0.44203076, 0.8107121, 0.47249195,...  
1  [0.78343225, 0.4830486, 0.9525863, 0.50286084,...  
2  [0.7510135, 0.46772155, 0.8101114, 0.41914812,...  
3  [0.8190234, 0.49838206, 0.8504915, 0.44808054,...  
4  [0.85232306, 0.46574005, 0.7150654, 0.40895066...

In [8]:
def covert_string_toarray_train(train_object):
  size_train=train_object.shape[0]
  print(size_train)
  for i in range(size_train):
    train_image['features'][i]=np.fromstring(train_image['features'][i][1:-1], sep=',')

In [9]:
def covert_string_toarray_dev(dev_object):
  size_dev=dev_object.shape[0]
  print(size_dev)
  for i in range(size_dev):
    dev_image['features'][i]=np.fromstring(dev_image['features'][i][1:-1], sep=',')

In [10]:
covert_string_toarray_train(train_image['features'])

8499


<ipython-input-8-cd44a5fe1f26>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_image['features'][i]=np.fromstring(train_image['features'][i][1:-1], sep=',')


In [11]:
covert_string_toarray_dev(dev_image['features'])

500


<ipython-input-9-a89436516ec0>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dev_image['features'][i]=np.fromstring(dev_image['features'][i][1:-1], sep=',')


In [12]:
train_image

index     id        img  label  \
0         0   1235  01235.png      1   
1         1   1236  01236.png      0   
2         2   1243  01243.png      0   
3         3   1245  01245.png      1   
4         4   1247  01247.png      1   
...     ...    ...        ...    ...   
8494   8495  98752  98752.png      0   
8495   8496  98754  98754.png      1   
8496   8497  98756  98756.png      1   
8497   8498  98762  98762.png      0   
8498   8499  98764  98764.png      0   

                                                   text  \
0     when you're feeling horny asf but your habibi ...   
1                      meanwhile at the isis strip club   
2     when your human says "who' s a good girl?" and...   
3     and that was the last nativity play my son was...   
4         you can't be racist if there is no other race   
...                                                 ...   
8494                                    shut up ontario   
8495  400 years of slavery rape and murder but now s...   
8496  this dude wants to use the same restroom as yo...   
8497              child in poverty with empty water jug   
8498               african kids dancing and celebrating   

                                               features  
0     [0.71356636, 0.4687377, 0.7601375, 0.47391602,...  
1     [0.7574666, 0.49860162, 0.8951834, 0.45049658,...  
2     [0.8522473, 0.49101305, 0.8114812, 0.43492022,...  
3     [0.81344944, 0.42663395, 0.7078128, 0.45056176...  
4     [0.75893325, 0.44350454, 0.7556687, 0.39917853...  
...                                                 ...  
8494  [0.8344943, 0.4936527, 0.8207589, 0.42816097, ...  
8495  [0.84529525, 0.4983647, 0.66996914, 0.52622557...  
8496  [0.7446378, 0.5141362, 0.8126955, 0.46491468, ...  
8497  [0.8350415, 0.39081714, 0.721996, 0.47131905, ...  
8498  [0.90392286, 0.4722435, 0.83153534, 0.4479324,...  

[8499 rows x 6 columns]

In [13]:
dev_image

id        img  label  \
0     1268  01268.png      0   
1     1456  01456.png      1   
2     1726  01726.png      1   
3     1742  01742.png      0   
4     1765  01765.png      1   
..     ...        ...    ...   
495  98235  98235.png      0   
496  98543  98543.png      1   
497  98547  98547.png      0   
498  98701  98701.png      1   
499  98720  98720.png      0   

                                                  text  \
0    father and daughter bonding time is the best l...   
1              they see them rollin..... they hating..   
2          a real man loads the dishwasher every night   
3    in just one hour from now i'll only have 4 hou...   
4    after a girl dies, what organ in her body stay...   
..                                                 ...   
495                                  fashion forward !   
496                                       upper downer   
497  waves mexican flag doesn't want to live in mexico   
498                        oh no i can't steal anymore   
499  when your wife just died giving birth to your ...   

                                          cleaned_text  \
0    father daughter bonding time best like share a...   
1                                    see rollin hating   
2                 real man load dishwasher every night   
3                one hour ill hour left work mere hour   
4                    girl dy organ body stay warm dick   
..                                                 ...   
495                                    fashion forward   
496                                       upper downer   
497          wave mexican flag doesnt want live mexico   
498                              oh cant steal anymore   
499  wife died giving birth daughter youre alone ro...   

                                              features  
0    [0.8011039, 0.44203076, 0.8107121, 0.47249195,...  
1    [0.78343225, 0.4830486, 0.9525863, 0.50286084,...  
2    [0.7510135, 0.46772155, 0.8101114, 0.41914812,...  
3    [0.8190234, 0.49838206, 0.8504915, 0.44808054,...  
4    [0.85232306, 0.46574005, 0.7150654, 0.40895066...  
..                                                 ...  
495  [0.7852769, 0.48783457, 0.8366222, 0.45380473,...  
496  [0.80557775, 0.46072176, 0.8657845, 0.4993673,...  
497  [0.83897704, 0.51914185, 0.860897, 0.417642, 0...  
498  [0.8463239, 0.52804404, 0.87455803, 0.46315646...  
499  [0.7125783, 0.48747504, 0.7889395, 0.4683179, ...  

[500 rows x 6 columns]

In [14]:
X_train=[]
for i in range(train_image.shape[0]):
  X_train.append(np.array(train_image['features'][i]))
X_train=np.array(X_train)

In [15]:
X_dev=[]
for i in range(dev_image.shape[0]):
  X_dev.append(np.array(dev_image['features'][i]))
X_dev=np.array(X_dev)

In [16]:
X_train.shape

(8499, 2048)

In [17]:
X_dev.shape

(500, 2048)

In [18]:
y_train=np.array(train_image['label'])

In [19]:
y_dev=np.array(dev_image['label'])

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.svm import LinearSVC
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import learning_curve

Model1-Logistic Regression

In [21]:
model=LogisticRegression(max_iter=1000)

In [22]:
history=model.fit(X_train,y_train)

In [23]:
X_predication=model.predict(X_dev)

In [24]:
accuracy_score(X_predication,y_dev)

0.496

In [25]:
confusion_matrix(X_predication,y_dev)

array([[208, 210],
       [ 42,  40]])

In [26]:
fpr, tpr, thresholds = roc_curve(X_predication,y_dev)
aucroc = auc(fpr, tpr)
print("AUCROC: ", aucroc)

AUCROC:  0.49270626677558643


Model2-XgboostClassifier

In [27]:
from xgboost import XGBClassifier

In [28]:
model2=XGBClassifier()

In [29]:
model2.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [30]:
X_predication=model2.predict(X_dev)

In [31]:
accuracy_score(X_predication,y_dev)

0.5

In [32]:
confusion_matrix(X_predication,y_dev)

array([[214, 214],
       [ 36,  36]])

In [33]:
fpr, tpr, thresholds = roc_curve(X_predication,y_dev)
aucroc = auc(fpr, tpr)
print("AUCROC: ", aucroc)

AUCROC:  0.5


Model3-SVM

In [34]:
model3=LinearSVC(max_iter=10000,penalty='l2')

In [35]:
model3.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC(max_iter=10000)

In [36]:
X_predication=model3.predict(X_dev)

In [37]:
accuracy_score(X_predication,y_dev)

0.502

In [38]:
confusion_matrix(X_predication,y_dev)

array([[181, 180],
       [ 69,  70]])

In [39]:
fpr, tpr, thresholds = roc_curve(y_dev,X_predication)
aucroc = auc(fpr, tpr)
print("AUCROC: ", aucroc)

AUCROC:  0.502
